### ISSUE TITLE
Creating an Order

### ISSUE THREAD

**Issue by jmejia** [michael-reeves/redrum_nursery#13]
Background: An existing user and a cart with products

As a visitor
When I visit "/cart"
And I click "Checkout"
Then I should be required to login

When I am logged in
And I visit "/cart"
And I click "Checkout"
Then the order should be placed
And my current page should be "/orders"
And I should see a message "Order was successfully placed"
And I should see the order I just placed in a table

**Comment by sabondano** [comment]
@mdorrance @michael-reeves @imwithsam 
I started to work on the tests for the order model class but couldn't create the orders table to get this rolling since we don't have the users table yet, which is needed for the orders. 

The orders table needs to have a foreign key (user_id) to work. Just FYI. Im going to start creating the view in the meantime and as soon as we have issue #14 (Authenticated User) merged to master we can start moving a little faster on Creating an Order (issue #13).

Let me know if we're on the same page or if you can think of a better way to handle or think about this.

**Comment by jmejia** [comment]
@sabondano Great comment :+1:

**Comment by mdorrance** [comment]
@sabondano can you add the user_id column later? @imwithsam  and I are TDDing our way through Authentication and it will be awhile. One "click" leads to a whole new set of "need to create". We can currently create an account but now we need to change direction and create a Session.

We have the Users table built with user#new, user#create and user#show (which renders as /dashboard). We have to move to Session logic to change the navbar message and Login/Logout. We are hoping to finish in about another hour.

**Comment by sabondano** [comment]
@mdorrance not sure if it's a good or bad idea to build the create order feature without the user_id column in the orders table. Will experiment with it a little bit and let you know what I find out.

What do you think of this first draft for an orders index view? Anything you would change?

![screen shot 2015-08-06 at 9 48 53 pm](https://cloud.githubusercontent.com/assets/1958868/9128446/0999a572-3c86-11e5-8626-131c9fdf078d.png)
